### ISSUE TITLE
A question about __main_void

### ISSUE THREAD

**Issue by yamt** [dicej/component-linking-demo#2]
why have you excluded __main_void.o from libc?
https://github.com/dicej/wasi-libc/commit/4631fa660ff3445ddd42774e6e744c5203acb2f1
i'm not sure how non-void main can work without it.
was it a temporary workaround?

**Comment by dicej** [comment]
When it __main_void.o is included, libc.so imports `main_argc_argv`, and thus the application must define it, even if it's not a command.  I didn't realize it would prevent creating command apps.  Perhaps @sunfishcode has ideas how to handle both scenarios gracefully.

**Comment by sunfishcode** [comment]
Would it work to make the `__main_argc_argv` import in `__main_void.o` weak, and include `__main_void.o` in libc.so? I'm not sure if weak imports work in our .so files yet, but if so, that might be an option.

If that doesn't work, perhaps we could make the `__main_void` declaration in crt1-command.c weak. I wrote up this untested patch to illustrate the idea: https://github.com/WebAssembly/wasi-libc/tree/sunfishcode/dso-main

**Comment by yamt** [comment]
> When it __main_void.o is included, libc.so imports `main_argc_argv`, and thus the application must define it, even if it's not a command. I didn't realize it would prevent creating command apps. Perhaps @sunfishcode has ideas how to handle both scenarios gracefully.

i see.
i haven't noticed as my implementation does lazy binding.

**Comment by dicej** [comment]
Thanks, @sunfishcode.  I'll admit I've never heard of weak imports before, and from the documentation for `WASM_SYM_BINDING_WEAK` in https://github.com/WebAssembly/tool-conventions/blob/main/Linking.md, it seems that the flag only has meaning for definitions, not imports, so I don't think that's an option for us (happy to be corrected about that, though).

I'll try your weak `__main_void` idea.  If that doesn't work, perhaps I could add a weak, no-op `main_argc_argv` to `__main-void.c, instead.

**Comment by yamt** [comment]
FYI, i have some simple tests: https://github.com/yamt/garbage/tree/master/c/shlib

**Comment by yamt** [comment]
> Thanks, @sunfishcode. I'll admit I've never heard of weak imports before, and from the documentation for `WASM_SYM_BINDING_WEAK` in https://github.com/WebAssembly/tool-conventions/blob/main/Linking.md, it seems that the flag only has meaning for definitions, not imports, so I don't think that's an option for us (happy to be corrected about that, though).

WASM_SYM_BINDING_WEAK is availabile in the WASM_DYLINK_IMPORT_INFO subsection, which you should look at for imports IIUC.

emscripten: https://github.com/emscripten-core/emscripten/blob/87b495148dc361a5cbdc020408e7a0420f730a0b/src/library_dylink.js#L495-L503
toywasm: https://github.com/yamt/toywasm/blob/6a30dac8e1b8ef1c147ca3137262819e47c9573a/lib/dyld.c#L184-L200

**Comment by yamt** [comment]
> Would it work to make the `__main_argc_argv` import in `__main_void.o` weak, and include `__main_void.o` in libc.so?

i confirmed this works with a runtime linker with weak symbol implemented.

**Comment by dicej** [comment]
I've addressed this using Dan's weak import suggestion.  When `wit-component` sees a weak import with no corresponding definition, it will satisfy it using a synthesized trapping stub function.
